'del': secured rm ; 'list': only using . ./.git ./.git/index ./.git/ORIG_HEAD ./.git/objects ./.git/objects/d2 ./.git/objects/d2/e32fbd5757e0b2a38d304e9da0e6e914389db2 ./.git/objects/91 ./.git/objects/91/bc3e27413a7055d3bd2fbc99f8546a01349666 ./.git/objects/b3 ./.git/objects/b3/59d3c30c36cf6d64411a9a9f997d3544904b1c ./.git/objects/a5 ./.git/objects/a5/251bf2095f5e2f2cc43dc98ed01455bd152fa0 ./.git/objects/info ./.git/objects/2d ./.git/objects/2d/9cbc41b1f6cc019037d951f89a89952a6507b0 ./.git/objects/79 ./.git/objects/79/7adeb1ed9c89325041557174e9ddb8a4469426 ./.git/objects/b7 ./.git/objects/b7/eb7a7eef74d532cc3b25cc3887fb997be945a7 ./.git/objects/22 ./.git/objects/22/fdb877b229a3df536dd205f0d0da9bee00370d ./.git/objects/be ./.git/objects/be/ffad0d9b68f520a466d189b56661694adc616e ./.git/objects/78 ./.git/objects/78/54bb613cca966b73fb2515cfe80cab42583cde ./.git/objects/4b ./.git/objects/4b/825dc642cb6eb9a060e54bf8d69288fbee4904 ./.git/objects/eb ./.git/objects/eb/e6447c9b818b1bf18e5d99a2cb19cb9c400749 ./.git/objects/pack ./.git/objects/1c ./.git/objects/1c/4c4993f52a159c9a44235e9f1b44c189109885 ./.git/objects/63 ./.git/objects/63/c5daa3f0d4e1891722974640bce354965d1cb8 ./.git/objects/30 ./.git/objects/30/bf774096c0402381f66f838554ed49702d82fa ./.git/info ./.git/info/exclude ./.git/branches ./.git/refs ./.git/refs/remotes ./.git/refs/remotes/origin ./.git/refs/remotes/origin/master ./.git/refs/tags ./.git/refs/heads ./.git/refs/heads/master ./.git/description ./.git/COMMIT_EDITMSG ./.git/config ./.git/hooks ./.git/hooks/applypatch-msg.sample ./.git/hooks/pre-applypatch.sample ./.git/hooks/fsmonitor-watchman.sample ./.git/hooks/update.sample ./.git/hooks/commit-msg.sample ./.git/hooks/post-update.sample ./.git/hooks/pre-push.sample ./.git/hooks/prepare-commit-msg.sample ./.git/hooks/pre-commit.sample ./.git/hooks/pre-rebase.sample ./.git/hooks/pre-receive.sample ./.git/logs ./.git/logs/refs ./.git/logs/refs/remotes ./.git/logs/refs/remotes/origin ./.git/logs/refs/remotes/origin/master ./.git/logs/refs/heads ./.git/logs/refs/heads/master ./.git/logs/HEAD ./.git/FETCH_HEAD ./.git/HEAD ./README.md ./vem

diff --git a/vem b/vem
--- a/vem
+++ b/vem
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-VENV_PATH="$HOME/.virtual-env"
+export VENV_PATH="${VENV_PATH:-$HOME/.virtual-env}"
 
 usage() {
   echo "usage:"
@@ -23,74 +23,73 @@ fi
 
 case "$1" in
   "-h"|"--help"|"help"|"h")
-  	usage
-  	exit 0
-  	;;
+    usage
+    exit 0
+    ;;
 
   "list")
-  	for env in $(find "${VENV_PATH}" -maxdepth 1 -type "d"); do
-  	  echo "$env"
-  	done
-  	exit 0
-  	;;
+    # mindepth to hide VENV_PATH from output
+    find "${VENV_PATH}" -mindepth 1 -maxdepth 1 -type "d" -exec basename "{}" \;
+    exit 0
+    ;;
 
   "get")
-  	if [ -z "$VIRTUAL_ENV" ]; then
-  	  echo "no env set yet"
-  	else
-  	  echo "current env: $VIRTUAL_ENV"
-  	fi
-  	exit 0
-  	;;
+    if [ -z "$VIRTUAL_ENV" ]; then
+      echo "no env set yet"
+    else
+      echo "current env: $VIRTUAL_ENV"
+    fi
+    exit 0
+    ;;
 
   "set")
-  	if [ -z "$2" ]; then
-  	  usage
-  	  exit 1
-  	fi
-  	if [ ! -d "$VENV_PATH/$2" ]; then
-  	  echo "env not found: $2"
-  	  exit 2
-  	fi
+    if [ -z "$2" ]; then
+      usage
+      exit 1
+    fi
+    if [ ! -d "$VENV_PATH/$2" ]; then
+      echo "env not found: $2"
+      exit 2
+    fi
 
-	echo "env set: $2"
-  	export VIRTUAL_ENV="$VENV_PATH/$2"
-  	export PATH="${VIRTUAL_ENV}/bin:$PATH"
-  	unset "PYTHON_HOME"
-  	exec "$SHELL"
-  	;;
+    echo "env set: $2"
+    export VIRTUAL_ENV="$VENV_PATH/$2"
+    export PATH="${VIRTUAL_ENV}/bin:$PATH"
+    unset "PYTHON_HOME"
+    exec "$SHELL"
+    ;;
 
   "link")
-	if [ ! -d "$VENV_PATH/$2" ]; then
-	  echo "env not found: $2"
-	fi
+    if [ ! -d "$VENV_PATH/$2" ]; then
+      echo "env not found: $2"
+    fi
 
-	ln -s "$VENV_PATH/$2" "$3"
-  	echo "env linked ($2) to $3"
-  	exit 0
-  	;;
+    ln -s "$VENV_PATH/$2" "$3"
+    echo "env linked ($2) to $3"
+    exit 0
+    ;;
 
   "gen")
-  	if [ -z "$2" ]; then
-  	  usage
-  	  exit 1
-  	fi
-  	virtual-env "$VENV_PATH/$2"
-  	echo "env created: $2 ($VENV_PATH/$2)"
-  	exit 0
-  	;;
+    if [ -z "$2" ]; then
+      usage
+      exit 1
+    fi
+    virtual-env "$VENV_PATH/$2"
+    echo "env created: $2 ($VENV_PATH/$2)"
+    exit 0
+    ;;
 
   "del")
-  	if [ -z "$2" ]; then
-  	  usage
-  	  exit 1
-  	fi
-  	echo "env deleted: $2"
-  	rm -rf "$VENV_PATH/$2"
-  	exit 0
-  	;;
+    if [ -z "$2" ]; then
+      usage
+      exit 1
+    fi
+    echo "env deleted: $2"
+    rm -rf "${VENV_PATH:?}/$2"
+    exit 0
+    ;;
 
   *)
-  	usage
-  	exit 1
+    usage
+    exit 1
 esac
